name: Cypress Testes

on: [push]

jobs: 
  cypres-electron-testes:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: yarn install
        
      - name: Run E2E testes
        run: yarn cypress run
      
